services:
  document-processor:
    build: .
    container_name: document-processor
    restart: unless-stopped
    env_file:
      - ./.env  # Explicitly load the .env file from the current directory
    volumes:
      - /volume1/Docker/gemini-ocr-flow/inbox:/docs/inbox
      - /volume1/Famille/SCAN:/docs/processed
      - /volume1/Docker/gemini-ocr-flow/error:/docs/error
      - /volume1/Docker/gemini-ocr-flow/tmp:/docs/tmp
      - /var/run/docker.sock:/var/run/docker.sock
